### ISSUE TITLE
CMake find_package()

### ISSUE THREAD

**Issue by jliu309** [asorbini/rticonnextdds-ros2-helpers#1]
I noticed there isn't any `Find<package>.cmake` or `<package>Config.cmake` file in the repository. Do I need to write one on my own to make sure that CMake can find it? Or is there any way to build the packages? Any of your help will be greatly appreciated!

**Comment by asorbini** [comment]
Hi @jliu309,

This repository contains ROS 2 packages meant to be built with the `ament` build system which automatically generates cmake scripts to load them as dependencies from other packages.

I suggest referring to the ROS 2 documentation for more information on packages and the ROS 2 build system (e.g. [this tutorial](https://docs.ros.org/en/rolling/Tutorials/Beginner-Client-Libraries/Creating-Your-First-ROS2-Package.html)).
